name: Kjør scraper hver time

on:
  schedule:
    - cron: "0 6 * * *" # Hver dag
  workflow_dispatch: # Lar deg kjøre manuelt fra GitHub

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Henter hele git-historikken

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer avhengigheter
        run: |
          pip install -r requirements.txt || echo "Ingen requirements.txt"

      - name: Kjør scraper
        run: python scraper.py

      - name: Commit og push oppdatert CSV
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add meta.csv google.csv
          git pull --rebase https://x-access-token:$TOKEN@github.com/${{ github.repository }} main
          git commit -m "Oppdater CSV" || echo "Ingen endringer"
          git push https://x-access-token:$TOKEN@github.com/${{ github.repository }} HEAD:main
