name: Kjør scraper daglig

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Hent hele historikken

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer avhengigheter
        run: |
          pip install -r requirements.txt || echo "Ingen requirements.txt"

      - name: Kjør scraper
        run: python scraper.py

      - name: Commit og push CSV hvis endringer
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}

          git add meta.csv google.csv
          git diff --cached --quiet && echo "Ingen endringer – hopper over push" && exit 0

          git commit -m "Oppdater CSV"
          git fetch origin main
          git rebase origin/main
          git push origin HEAD:main
