name: Kjør scraper hver time

on:
  schedule:
    - cron: "0 * * * *" # Hver time
  workflow_dispatch: # Lar deg kjøre manuelt fra GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer avhengigheter
        run: |
          pip install -r requirements.txt || echo "Ingen requirements.txt"

      - name: Kjør scraper
        run: python hamar.py

      - name: Commit og push oppdatert CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add hamar.csv
          git commit -m "Oppdater CSV" || echo "Ingen endringer"
          git push
